commit 7

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,4 +1,4 @@
-name: CI_new135
+name: CI_new136
 
 on:
   release:
@@ -22,11 +22,11 @@ jobs:
 
       - name: Log in to GitHub Container Registry
         run: |
-          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || { echo "Error: Failed to authenticate to GitHub Container Registry."; exit 1; }
+          echo "${{ secrets.GHCR_SECRET }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin || { echo "Error: Failed to authenticate to GitHub Container Registry."; exit 1; }
 
       - name: Build and push Docker image for release
         env:
-          IMAGE_NAME: ghcr.io/witglobal/pico-boilerplate
+          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
         run: |
           TAG="${{ github.event.release.tag_name }}"
           echo "Building Docker image with tag: $TAG"
